import React from 'react'
import type { NextPage } from 'next'
import { useAppContext } from './api/context'
import Head from 'next/head'
import Navigation from '../components/navigation'
import * as Layouts from '../components/layouts'
import VideoList from '../components/video-list'
import Lottie from 'react-lottie'
import { LoadingIcon } from '../components/lotties'

const defaultLottieOptions = {
  loop: true,
  autoplay: true,
  animationData: LoadingIcon,
  rendererSettings: {
    preserveAspectRatio: 'xMidYMid slice',
  },
}

const Home: NextPage = ({ props }: any) => {
  const { loading, results } = useAppContext()

  return (
    <div className="w-full h-screen">
      <Head>
        <title className="text-2xl">Next.js and Youtube Search</title>
        <meta
          name="description"
          content="Youtube Search generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full min-h-[calc(100%_-_40px)] bg-black-base">
        <Navigation />
        <div className="pt-10 pb-20">
          {loading ? (
            <div className="w-full h-full flex items-center justify-center">
              <Lottie
                options={defaultLottieOptions}
                height={400}
                width={400}
                isStopped={false}
                isPaused={false}
              />
            </div>
          ) : (
            <VideoList {...{ results }} />
          )}
        </div>
      </main>
      <Layouts.Footer />
    </div>
  )
}

export default Home
