import React, { useCallback, useState } from 'react'
import debounce from 'lodash.debounce'
import type { NextPage } from 'next'
import Head from 'next/head'
import Navigation from '../components/navigation'
import { API } from './api/constant'
import * as Layouts from '../components/layouts'
import VideoList from '../components/video-list'

const Home: NextPage = ({ data }: any) => {
  console.log('data:', data)

  const [results, setResults] = useState(null)

  const handleChange = debounce((value, maxResults) => {
    const url = `${API.YOUTUBE_SEARCH}search?key=${process.env.NEXT_PUBLIC_YOUTUBE_API_KEY}&type=video&part=snippet&maxResults=${maxResults}&q=${value}`
    console.log(url, value, maxResults)
    fetch(url)
      .then((res) => res.json())
      .then((json) => setResults(json))
  }, 500)

  console.log(results)

  return (
    <div className="w-full h-screen">
      <Head>
        <title className="text-2xl">Next.js and Youtube Search</title>
        <meta
          name="description"
          content="Youtube Search generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full min-h-[calc(100%_-_40px)] bg-black-base">
        <Navigation onChange={handleChange} />
        <div className="pt-10 pb-20">
          <VideoList {...{ results }} />
        </div>
      </main>
      <Layouts.Footer />
    </div>
  )
}

export default Home
